export default class QueryKey {
    static GET_CARD_DATA = 'GET_CARD_DATA';
    static GET_LOGIN_USER_DETAIL = 'GET_LOGIN_USER_DETAIL';
    static GET_BENEFICIARY = 'GET_BENEFICIARY';
    static GET_COUNTRY = 'GET_COUNTRY';
    static GET_CURRENCY = 'GET_CURRENCY';
    static GET_ACCOUNT_TYPE_DATA = 'GET_ACCOUNT_TYPE_DATA';
    static GET_ACCOUNTS_AND_ASSETS = 'GET_ACCOUNTS_AND_ASSETS';
    static GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
    static GET_ASSET_BALANCE = 'GET_ASSET_BALANCE';
    static GET_CURR_ACCOUNTS = 'GET_CURR_ACCOUNTS';
    static GET_CARDS_RULES = 'GET_CARDS_RULES';
    static GET_PUBLIC_KEY = 'GET_PUBLIC_KEY';
    static GET_TRANSACTIONS = 'GET_TRANSACTIONS';

  }