// Auth Routes
export enum Auth_ROUTES {
  LOGIN = "LOGIN",
  FORGETPASSWORD = "FORGETPASSWORD",
  SETPASSWORD = "SETPASSWORD",
  CREATEACCOUNT = "CREATEACCOUNT",
  WELCOME = "WELCOME",
  LOGIN_SECURE_PASS = "LOGIN_SECURE_PASS"



}

// Home Routes

export enum HOME_ROUTES {
  HOME = "HOME",
  ACCOUNT = "ACCOUNT",
  PAYMENT = "PAYMENT",
  CARD = "CARD",
  CREATE_VC = "CREATE_VC",
  CREATE_PC = "CREATE_PC",
  ConfirmCardRequest = "ConfirmCardRequest",
  PIN_SECURITY = "PIN_SECURITY",
  REPLACE_CARD = "REPLACE_CARD",
  SET_LIMIT = "SET_LIMIT",
  TRANSACTIONHISTORY = "TRANSACTIONHISTORY",
  MORE = "MORE",
  CONTACTADDRESS = "CONTACTADDRESS",
  PROFILE = "PROFILE",
  UpdatePassword = "UpdatePassword",
  TABSTACK = 'TABSTACK',
  CURRENCY_EXCHANGE = 'TABSTACK',
  CONVERSION_HISTORY = "CONVERSION_HISTORY",
  BENEFICIARY_LIST = "BENEFICIARY_LIST",
  BENEFICIARY_MANAGEMENT = "BENEFICIARY_MANAGEMENT",
  ADD_NEW_BENEFICIARY = "ADD_NEW_BENEFICIARY",
  FAQ = "FAQ",
  SUPPORT = "SUPPORT",
  PRIVACY_POLICY = "PRIVACY",
  TERMS_USE = "TERMS_USE",
  CONFIRM_CURENCY_EXCHANGE = "CONFIRM_CURENCY_EXCHANGE",
  ACCOUNT_DETAIL = "ACCOUNT_DETAIL",
  NOTIFICATION = "NOTIFICATION",
  MAKE_PAYMENT = "MAKE_PAYMENT",
  MY_ACCOUNT_TRANSFER = "MyAccountTransfer",
  INTERNATIONAL_TRANSFER = "INTERNATIONAL_TRANSFER",
  BANK_TRANSFER = "BANK_TRANSFER"

}
