// Auth Routes
export enum Auth_ROUTES {
  LOGIN = "LOGIN",
  FORGETPASSWORD = "FORGETPASSWORD",
  SETPASSWORD = "SETPASSWORD",
  CREATEACCOUNT = "CREATEACCOUNT",
  FORGET_PASS_RESET = "FORGET_PASS_RESET",
  WELCOME = "WELCOME",
  LOGIN_SECURE_PASS = "LOGIN_SECURE_PASS",
  OTPVERIFY = "OTPVERIFY",



}

// Home Routes

export enum HOME_ROUTES {
  HOME = "HOME",
  TRANSACTION_DETAIL= "TRANSACTION_DETAIL", 
  ACCOUNT = "ACCOUNT",
  PAYMENT = "PAYMENT",
  CARD = "CARD",
  CREATE_VC = "CREATE_VC",
  CREATE_PC = "CREATE_PC",
  ConfirmCardRequest = "ConfirmCardRequest",
  PIN_SECURITY = "PIN_SECURITY",
  ADD_NEW_CURRENCY_ACCOUNT = "ADD_NEW_CURRENCY_ACCOUNT",
  REPLACE_CARD = "REPLACE_CARD",
  SET_LIMIT = "SET_LIMIT",
  RELACE_CARD_CONFIRM = "RELACE_CARD_CONFIRM",
  TRANSACTIONHISTORY = "TRANSACTIONHISTORY",
  UPDATE_ADDRESS = "UPDATE_ADDRESS",
  MORE = "MORE",
  CONTACTADDRESS = "CONTACTADDRESS",
  PROFILE = "PROFILE",
  REQUEST = "REQUEST",
  UpdatePassword = "UpdatePassword",
  TABSTACK = 'TABSTACK',
  CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE',
  CONVERSION_HISTORY = "CONVERSION_HISTORY",
  BENEFICIARY_LIST = "BENEFICIARY_LIST",
  BENEFICIARY_MANAGEMENT = "BENEFICIARY_MANAGEMENT",
  ADD_NEW_BENEFICIARY = "ADD_NEW_BENEFICIARY",
  FAQ = "FAQ",
  SUPPORT = "SUPPORT",
  PRIVACY_POLICY = "PRIVACY",
  TERMS_USE = "TERMS_USE",
  CONFIRM_CURENCY_EXCHANGE = "CONFIRM_CURENCY_EXCHANGE",
  ACCOUNT_DETAIL = "ACCOUNT_DETAIL",
  NOTIFICATION = "NOTIFICATION",
  ACCOUNT_STATEMENT = "ACCOUNT_STATEMENT",
  MAKE_PAYMENT = "MAKE_PAYMENT",
  MY_ACCOUNT_TRANSFER = "MyAccountTransfer",
  INTERNATIONAL_TRANSFER = "INTERNATIONAL_TRANSFER",
  BANK_TRANSFER = "BANK_TRANSFER",
  //Admin
  ADMIN_PAYMENT_STATUS = "ADMIN_PAYMENT_STATUS", 
  ADMIN_BENEFICIAY_STATUS = "ADMIN_BENEFICIAY_STATUS",
  ADMIN_CARD_STATUS = "ADMIN_CARD_STATUS"

}
