# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '13.0'

# prepare_react_native_project!

# target 'forntier_pay_mobile_app' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )
#   end
# end


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

prepare_react_native_project!

use_frameworks! :linkage => :static

target 'forntier_pay_mobile_app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # 🔥 Firebase fix
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end




# # platform :ios, min_ios_version_supported
# platform :ios, '16.0'
# # prepare_react_native_project!

# require_relative '../node_modules/react-native/scripts/react_native_pods'

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'forntier_pay_mobile_app' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   # 🔥 Firebase (modular headers fix)
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseMessaging', :modular_headers => true
#   pod 'FirebaseCoreInternal', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true
#   pod 'FirebaseInstallations', :modular_headers => true
#   pod 'FirebaseAnalytics', :modular_headers => true


#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )

#     # Apple Silicon simulator fix
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#         config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#       end
#     end
#   end
# end
