export default class ActionType {
  static USER_DATA = 'USER_DATA'; 
  static UPDATE_TOKEN = 'UPDATE_TOKEN';
  static LOGIN_USER_DATA = 'LOGIN_USER_DATA';  
  static SAVE_FCM = 'SAVE_FCM';
  static LOGOUT = 'LOGOUT';
  static LOADER = 'LOADER'; 
  static GET_COUNTRY = 'GET_COUNTRY';
  static GET_CURRENCY = 'GET_CURRENCY';
  static GET_BENEFICIARY = 'GET_BENEFICIARY';
  static GET_ACCOUNT_TYPE_DATA = 'GET_ACCOUNT_TYPE_DATA';
  static GET_CURR_ACCOUNTS = 'GET_CURR_ACCOUNTS';
  static GET_ACCOUNTS = 'GET_ACCOUNTS';
  static USER_LOGGEDIN = 'USER_LOGGEDIN';
  static SELECTED_ACCOUNT_WHOLE_APP = 'SELECTED_ACCOUNT_WHOLE_APP';

    // 🔔 Notification related
  static SET_PENDING_TRANSACTION = 'SET_PENDING_TRANSACTION';
  static MARK_TRANSACTION_HANDLED = 'MARK_TRANSACTION_HANDLED';
  static CLEAR_PENDING_TRANSACTION = 'CLEAR_PENDING_TRANSACTION';

  static  ENQUEUE_TRANSACTION= 'ENQUEUE_TRANSACTION';
  static DEQUEUE_TRANSACTION= 'DEQUEUE_TRANSACTION';
  static CLEAR_QUEUE= 'CLEAR_QUEUE';
  static CARD_SCREEN_REFRESH= 'CARD_SCREEN_ACTION_REFRESH';
  static ACCOUNT_SCREEN_REFRESH= 'ACCOUNT_SCREEN_REFRESH';
}
